'use client';

import AppTopbar from './AppTopbar';
import AppSidebar from './AppSidebar';
import AppFooter from './AppFooter';

export default function AppLayout({ children }: { children: React.ReactNode }) {
    return (
        <div className="layout-wrapper">
            <AppTopbar />
            <AppSidebar />

            <div className="layout-main-container">
                <div className="layout-main">{children}</div>
                <AppFooter />
            </div>
        </div>
    );
}

// import { AppLayout } from './context/layoutcontext';
// import { PrimeReactProvider } from 'primereact/api';
// import 'primereact/resources/primereact.css';
// import '../app/styles/layout/layout.scss';
// import '../app/styles/demo/Demos.scss';

// interface AppLayoutProps {
//     children: React.ReactNode;
// }

// export default function AppLayout({ children }: AppLayoutProps) {
//     return (
//         <html lang="en" suppressHydrationWarning>
//             <head>
//                 <title>UI JSX Sakai</title>
//                 <link id="favicon" type="image/x-icon" href="/favicon.svg" rel="icon"/>
//                 <link id="theme-css" href={`/themes/lara-light-indigo/theme.css`} rel="stylesheet"></link>
//             </head>
//             <body>
//                 <PrimeReactProvider>
//                     <LayoutProvider>{children}</LayoutProvider>
//                 </PrimeReactProvider>
//             </body>
//         </html>
//     );
// }

/*
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

// export default function RootLayout({
//     children,
// }: Readonly<{
//     children: React.ReactNode;
// }>) {
//     return (
//         <html lang="en">
//             <body className={`${geistSans.variable} ${geistMono.variable}`}>
//                 {children}
//             </body>
//         </html>
//     );
// }
*/
