services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_NODE_ENV: production
        VITE_API_URL: https://api-jdk.ledger-finance.com
        VITE_API_TIMEOUT_MS: 30000
        VITE_SESSION_WARNING_MS: 60000
        VITE_SESSION_DEBUG: "false"
    image: fpfluitsximg
    container_name: fpfl-ui-tsx
    ports:
      - '80:80'
