spring:
    application:
        name: module-api
    datasource:
        url: jdbc:postgresql://localhost:5432/FPFL-V2
        username: postgres
        password: password
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                default_schema: FPFL

server:
    port: 8000

security:
    jwt:
        secret: "your-very-long-256-bit-secret-key-here"
        # 15 seconds
        #access-token-expiration-ms: 30000
        #refresh-token-expiration-ms: 30000

        # 1 minute
        #access-token-expiration-ms: 60000
        #refresh-token-expiration-ms: 60000

        # 15 minutes
        access-token-expiration-ms: 900000
        refresh-token-expiration-ms: 900000

        # 7 days
        #refresh-token-expiration-ms: 604800000
