package com.financialplanner.moduleitemsbc.domain.repository;

import com.financialplanner.moduleitemsbc.infrastructure.persistence.entity.ItemType;

import java.util.List;
import java.util.Optional;

/**
 * Interface representing the repository for managing {@code ItemType} instances.
 * Provides CRUD operations for persisting and retrieving item type-related data
 * from the underlying data source.
 *
 * This interface serves as a contract for managing {@code ItemType} entities
 * and abstracts the persistence details, ensuring a consistent interaction
 * between the application and the data layer.
 */
public interface ItemTypeRepository {
    /**
     * Persists the given {@code ItemType} entity to the underlying data source.
     * If the entity already exists, it will be updated; otherwise, a new record
     * will be created.
     *
     * @param entity the {@code ItemType} entity to be saved, must not be null
     * @return the saved {@code ItemType} entity, potentially with updated values
     *         (e.g., autogenerated IDs or modified fields)
     */
    ItemType save(ItemType entity);

    /**
     * Retrieves an {@code ItemType} entity by its unique identifier.
     * This method queries the underlying data source to locate the {@code ItemType}
     * corresponding to the provided ID. If no matching entity is found, an empty
     * {@code Optional} is returned.
     *
     * @param id the unique identifier of the {@code ItemType} to be retrieved, must not be null
     * @return an {@code Optional} containing the found {@code ItemType}, or an empty {@code Optional} if not found
     */
    Optional<ItemType> findById(Long id);

    /**
     * Retrieves all instances of {@code ItemType} from the data source.
     * This method returns a complete list of {@code ItemType} entities
     * currently stored, allowing for operations that require access to
     * all records (e.g., displaying, filtering, or exporting data).
     *
     * @return a list of {@code ItemType} entities, or an empty list if no records are found
     */
    List<ItemType> findAll();

    /**
     * Removes the entity with the specified unique identifier from the data store.
     * This method is typically utilized to perform a delete operation by ID.
     *
     * @param id the unique identifier of the entity to be deleted; must not be null.
     */
    void deleteById(Long id);
}
