name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the API Docker image
      run: docker build ./API-JDK --file API-JDK/Dockerfile --tag fpfl-api:$(date +%s)
    - name: Build the UI Docker image
      run: docker build ./UI-TSX --file UI-TSX/Dockerfile --tag fpfl-ui:$(date +%s)
